---
title: "Stat-415/615 Project - Tidying Data"
author: "Naomi Carrigg, Conor Gillingham, Emily Randolph, Connor Rempe"
date: "10/31/24"
output:
  pdf_document: 
    toc: no
    toc_depth: 2
    number_sections: no
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r}
## cleaning/tidying the data
AirQuality_data_raw <- read_csv("Air_Quality_History.csv")

AirQuality_data <- AirQuality_data_raw %>%
  mutate(across(starts_with("PARAMETER_NAME"), 
                ~ str_replace_all(., " ", "_") %>%
                  str_to_lower() %>%
                  str_remove_all("[^a-z_]"))) %>%
  mutate(SITE_NAME = case_match(SITE_NUM, 
                                41 ~ "River_Terrace_NE", 
                                43 ~ "McMillan_NW", 
                                50 ~ "Takoma_Recreation_NW",
                                51 ~ "Anacostia_Freeway_NE", 
                                53 ~ "Greenleaf_Recreation_SW", 
                                42 ~ "Hains_Point_SW")) %>%
  select(-c(LONGITUDE, LATITUDE, STATE_CODE, STATE_NAME, COUNTY_NAME, POC, DATUM, OBJECTID, UNITS_OF_MEASURE, METHOD_CODE, METHOD_NAME, AQSID, CITY_NAME, CBSA_NAME, ADDRESS, LOCAL_SITE_NAME, SAMPLE_DURATION, EVENT_TYPE)) %>%
  mutate(DATETIME_LOCAL = as.POSIXct(DATETIME_LOCAL, tz = "UTC"),
         Year = year(DATETIME_LOCAL),
         Month = month(DATETIME_LOCAL, label = TRUE, abbr = TRUE) %>% as.character()) %>%
  mutate(Season = case_when(
    Month %in% c("Dec", "Jan", "Feb") ~ 'Winter',
    Month %in% c("Mar", "Apr", "May") ~ 'Spring',
    Month %in% c("Jun", "Jul", "Aug") ~ 'Summer',
    TRUE ~ 'Fall'
  ))

# Grouping and summarizing
AirQuality_data_means <- AirQuality_data %>%
  group_by(Season, SITE_NAME, Month, Year, PARAMETER_NAME) %>%
  summarize(ARITHMETIC_MEAN = mean(ARITHMETIC_MEAN, na.rm = TRUE), .groups = 'drop')

AirQuality_data_aqi <- AirQuality_data %>%
  group_by(Season, SITE_NAME, Month, Year, PARAMETER_NAME) %>%
  summarize(AQI = mean(AQI, na.rm = TRUE), .groups = 'drop')

# Pivot the data, 
# this is where the issue is with the NAs  because there are some cases which don't have any data for the 5  groups, we can keep these and just have a ton of NA's or choose which pollutants we want to focus on
AirQuality_data_means <- AirQuality_data_means %>%
  pivot_wider(names_from = PARAMETER_NAME, values_from = ARITHMETIC_MEAN)

AirQuality_data_aqi <- AirQuality_data_aqi %>%
  pivot_wider(names_from = PARAMETER_NAME, values_from = AQI)
```

```{r}
head(AirQuality_data_means)
tail(AirQuality_data_means)
head(AirQuality_data_aqi)
tail(AirQuality_data_aqi)
```


```{r}
#Columns with at least 1 non-NA AQI
AirQuality_data_aqi_reduced <- subset(AirQuality_data_aqi, select = c("Season", "SITE_NAME","Month", "Year", "carbon_monoxide","nitrogen_dioxide_no", "pm__local_conditions", "ozone", "pm_total_um_stp","sulfur_dioxide"))
```

```{r}
# means df with columns of interest
reduced_data <- AirQuality_data_means %>% 
  subset(select = c("Season", "SITE_NAME","Month", "Year", "barometric_pressure", "carbon_monoxide", "nitrogen_dioxide_no","outdoor_temperature", "pm__local_conditions","relative_humidity"	, "wind_direction__resultant", "wind_speed__resultant"))
```

```{r}
reduced_data %>% 
  ggplot(aes(x = barometric_pressure, y = carbon_monoxide)) +
  geom_point() +
  geom_smooth(method = 'lm', se = FALSE, color = 'red') +
  facet_wrap(~Year)
```


```{r}
# Get Descriptive Statistics for numeric colmns in means
descriptive_stats_means <- data.frame()

for (col in names(AirQuality_data_means)) {
  if (is.numeric(AirQuality_data_means[[col]])) {
    working_means <- AirQuality_data_means %>%
      summarise(
        variable = col,
        mean = mean(.data[[col]], na.rm = TRUE),
        median = median(.data[[col]], na.rm = TRUE),
        sd = sd(.data[[col]], na.rm = TRUE),
        min = min(.data[[col]], na.rm = TRUE),
        max = max(.data[[col]], na.rm = TRUE),
        n = sum(!is.na(.data[[col]]))
      )
        descriptive_stats_means <- bind_rows(descriptive_stats_means, working_means)
  }
}

print(descriptive_stats_means)
```


```{r}
# Descriptive stats for AQI
descriptive_stats_aqi <- data.frame()

for (col in names(AirQuality_data_aqi_reduced)) {
  if (is.numeric(AirQuality_data_aqi_reduced[[col]])) {
    working_means_aqi <- AirQuality_data_aqi_reduced %>%
      summarise(
        variable = col,
        mean = mean(.data[[col]], na.rm = TRUE),
        median = median(.data[[col]], na.rm = TRUE),
        sd = sd(.data[[col]], na.rm = TRUE),
        min = min(.data[[col]], na.rm = TRUE),
        max = max(.data[[col]], na.rm = TRUE),
        n = sum(!is.na(.data[[col]]))
      )
        descriptive_stats_aqi <- bind_rows(descriptive_stats_aqi, working_means_aqi)
  }
}

print(descriptive_stats_aqi)
```

columns_of_interest <- c("barometric_pressure", "carbon_monoxide", "nitrogen_dioxide_no","outdoor_temperature", "pm__local_conditions","relative_humidity"	, "wind_direction__resultant", "wind_speed__resultant")

```{r}
# Create a list of histograms for the specified columns
graph <- function(pollutant, name) {
  ggplot(reduced_data, aes(x = pollutant)) +
    geom_histogram(binwidth = 1, fill = 'lightblue', color = 'black', na.rm = TRUE) +
    labs(title = paste0('Histogram of ', name), x = name, y = 'Frequency') +
    theme_minimal()
}

graph(reduced_data$barometric_pressure, 'Barometric Pressure')
graph(reduced_data$carbon_monoxide, 'Carbon Monoxide')
graph(reduced_data$nitrogen_dioxide_no, 'Nitrogen Dioxide')
graph(reduced_data$outdoor_temperature, 'Temperature')
graph(reduced_data$pm__local_conditions, 'Particulate Matter')
graph(reduced_data$relative_humidity, 'Relatice Humidity')
graph(reduced_data$wind_direction__resultant, 'Wind Direction')
graph(reduced_data$wind_speed__resultant, 'Wind Speed')
```





